# Generated by Django 5.2.5 on 2025-08-31 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=80, verbose_name="Marca"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="Modelo"),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sistema Operativo"
                    ),
                ),
                (
                    "screen_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Tamaño Pantalla (pulgadas)",
                    ),
                ),
                (
                    "screen_resolution",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Resolución"
                    ),
                ),
                (
                    "ram_memory",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Memoria RAM"
                    ),
                ),
                (
                    "internal_storage",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Almacenamiento"
                    ),
                ),
                (
                    "main_camera",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Cámara Principal"
                    ),
                ),
                (
                    "front_camera",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Cámara Frontal"
                    ),
                ),
                (
                    "battery_capacity",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Batería (mAh)"
                    ),
                ),
                (
                    "connectivity",
                    models.TextField(blank=True, verbose_name="Conectividad"),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Procesador"
                    ),
                ),
                (
                    "graphics_card",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tarjeta Gráfica"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de Almacenamiento"
                    ),
                ),
                (
                    "storage_capacity",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Capacidad Almacenamiento",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "socket_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Socket/Compatibilidad"
                    ),
                ),
                (
                    "power_consumption",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Consumo Energético"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Frecuencia"
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tipo de Memoria"
                    ),
                ),
                (
                    "display_technology",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tecnología de Pantalla"
                    ),
                ),
                (
                    "refresh_rate",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Frecuencia de Refresco"
                    ),
                ),
                (
                    "audio_power",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Potencia Audio (W)"
                    ),
                ),
                (
                    "channels",
                    models.CharField(blank=True, max_length=20, verbose_name="Canales"),
                ),
                (
                    "platform_compatibility",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Compatibilidad Plataforma",
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=50, verbose_name="Género"),
                ),
                (
                    "multiplayer",
                    models.BooleanField(default=False, verbose_name="Multijugador"),
                ),
                (
                    "age_rating",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Clasificación Edad"
                    ),
                ),
                (
                    "additional_specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Especificaciones Adicionales",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_gaming",
        ),
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("celulares_tablets", "Celulares y Tablets"),
                    ("computadores", "Computadores y Periféricos"),
                    ("componentes", "Componentes y Hardware"),
                    ("audio_video", "Audio y Video"),
                    ("gaming", "Gaming"),
                ],
                default="computadores",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Destacado"),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Imagen Principal",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Descripción Corta"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad en Stock"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="catalog_pro_categor_891fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="catalog_pro_is_feat_b968c0_idx",
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="catalog.product",
            ),
        ),
    ]
