# Generated by Django 5.2.5 on 2025-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_alter_product_created_at_alter_product_updated_at"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_processed",
                        to="order.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSalesAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units_sold", models.BigIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("last_paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_agg",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["units_sold"], name="analytics_p_units_s_05a226_idx"
                    ),
                    models.Index(
                        fields=["revenue"], name="analytics_p_revenue_d73377_idx"
                    ),
                ],
            },
        ),
    ]
