# Generated by Django 5.2.5 on 2025-09-03 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="COP", max_length=6)),
                (
                    "method",
                    models.CharField(
                        choices=[("card", "Tarjeta")], default="card", max_length=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Iniciado"),
                            ("captured", "Capturado"),
                            ("failed", "Fallido"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="initiated",
                        max_length=12,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=12)),
                ("last4", models.CharField(blank=True, max_length=4)),
                ("auth_code", models.CharField(blank=True, max_length=16)),
                ("error_code", models.CharField(blank=True, max_length=32)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
