# Generated by Django 5.2.5 on 2025-08-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
