# Generated by Django 5.2.5 on 2025-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0002_remove_is_verified_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                verbose_name="Dirección de correo electrónico",
            ),
        ),
    ]
